10.3 : If the try block were to be removed then the program would
crash once it tried to run:
    int result = numerator / denominator
because the denominator is zero and would result in an
ArithmaticException exception.

10.4 : As long as you move it so that the try block attempts
to run the level3 function, it would work exactly the same
as the exception that would be caught in this class occurs
in the level3 function.

10.5 : It will catch any checked or unchecked exception that is thrown

10.6 : 
    ArithmaticException : Thrown when division by zero occurs.
    NullPointerException : Thrown when :
        - Calling an instance method of a null object
        - Accessing or modifing a field of a null object
        - Taking the length of null as if it were an array
        - Accessing or modifing the slots of null as if it
          were an array.
        - Throwing null as if it were a throwable value.
    NumberFormatException : A subclass of IllegalArgumentException.
    This exception is thrown when the application tries to convert
    a string into a numeric type but the string does not have the
    correct format.
    PatternSyntaxException : Another subclass of IllegalArgumentException
    An unchecked exception thrown when a syntax error in a regular
    expresion pattern.